micronautVersion=4.9.2
graalPythonVersion=24.2.2
jvmVersion=24
port=8181
graalVersion=24.0.2
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
gradle.startParameter.isConfigurationCache=true
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=2g -XX:+UseG1GC -XX:G1HeapRegionSize=32m
