micronautVersion=4.9.3
graalPythonVersion=25.0.0
jvmVersion=25
port=8181
graalVersion=25

#performance
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
#org.gradle.configureondemand=true
gradle.startParameter.isConfigurationCache=true
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=2g -XX:+UseG1GC -XX:G1HeapRegionSize=32m
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true